language: swift
osx_image: xcode9

cache:
  directories:
  - Carthage

env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - IOS_FRAMEWORK_SCHEME="SwiftQueue iOS"
  - MACOS_FRAMEWORK_SCHEME="SwiftQueue macOS"
  - TVOS_FRAMEWORK_SCHEME="SwiftQueue tvOS"
  - WATCHOS_FRAMEWORK_SCHEME="SwiftQueue watchOS"
  - WORKSPACE="SwiftQueue.xcodeproj"

  matrix:
    - PLATFORM="--platform iOS" DESTINATION="OS=11.0,name=iPhone X" SCHEME="$IOS_FRAMEWORK_SCHEME"   RUN_TESTS="NO"  POD_LINT="YES" DANGER="1"
    - PLATFORM="--platform iOS" DESTINATION="OS=8.1,name=iPhone 4S" SCHEME="$IOS_FRAMEWORK_SCHEME"   RUN_TESTS="NO"  POD_LINT="NO"  DANGER="0"
 
    - PLATFORM="--platform mac" DESTINATION="arch=x86_64"           SCHEME="$MACOS_FRAMEWORK_SCHEME" RUN_TESTS="YES" POD_LINT="NO"  DANGER="0"

before_install:
  # Run `Danger` if specified
  - if [ DANGER == "1" ]; then
      npm install -g danger;
      brew install danger/tap/danger-swift;
    fi

before_script:
  - swiftlint
  - carthage bootstrap $PLATFORM --cache-builds

script:
  # Run `Danger` if specified
  - if [ DANGER == "1" ]; then
      danger process danger-swift;
    fi
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

  # Build Framework in Debug and Run Tests if specified
  - if [ $RUN_TESTS == "YES" ]; then
      xcodebuild -project "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test -enableCodeCoverage YES | xcpretty;
    else
      xcodebuild -project "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty;
    fi

  # Run `pod lib lint` if specified
  - if [ $POD_LINT == "YES" ]; then
      pod lib lint;
    fi

after_success:
    - bash <(curl -s https://codecov.io/bash)
