language: swift
osx_image: xcode9

before_install:
  - brew install swiftlint

before_script:
  - carthage bootstrap --platform Mac

script:
    - swiftlint
    - set -o pipefail && xcodebuild test -enableCodeCoverage YES -project SwiftQueue.xcodeproj -scheme "SwiftQueue macOS" -sdk macosx10.13

after_success:
    - bash <(curl -s https://codecov.io/bash)
