language: objective-c
osx_image: xcode8.3
branches:
  only:
    - master
env:
  matrix:
    - DESTINATION="OS=4.0,name=Apple Watch - 42mm"
    - DESTINATION="OS=3.2,name=Apple Watch - 42mm"
    - DESTINATION="OS=2.0,name=Apple Watch - 42mm"

    - DESTINATION="OS=11.0,name=iPhone X"  
    - DESTINATION="OS=10.3.1,name=iPhone 7 Plus"  
    - DESTINATION="OS=9.0,name=iPhone 6"          
    - DESTINATION="OS=8.1,name=iPhone 4S"         

    - DESTINATION="OS=10.2,name=Apple TV 1080p"   
    - DESTINATION="OS=9.0,name=Apple TV 1080p"    

    - DESTINATION="arch=x86_64"
script:
  - set -o pipefail
  - swiftlint
  - xcodebuild test -enableCodeCoverage YES -project SwiftQueue.xcodeproj -scheme SwiftQueue -destination "$DESTINATION"
after_success:
    - bash <(curl -s https://codecov.io/bash)
