language: swift
osx_image: xcode9

before_install:
  - brew install swiftlint

before_script:
  - carthage bootstrap --platform iOS

script:
    - swiftlint
    - set -o pipefail && xcodebuild test -enableCodeCoverage YES -project SwiftQueue.xcodeproj -scheme SwiftQueue -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone X,OS=11.0'

after_success:
    - bash <(curl -s https://codecov.io/bash)
