language: swift
osx_image: xcode8.3

before_script:
    - xcodebuild -list

script:
    - set -o pipefail && xcodebuild test -enableCodeCoverage YES -project SwiftQueue.xcodeproj -scheme SwiftQueue -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6S,OS=9.1'

after_success:
    - bash <(curl -s https://codecov.io/bash)
