language: objective-c
osx_image: xcode8.3

script:
    - cd Example
    - pod install
    - xcodebuild -workspace SwiftQ.xcworkspace -scheme SwiftQ-Example -destination 'platform=iOS Simulator,name=iPhone 7 Plus,OS=10.3.1' -enableCodeCoverage YES build test
    
after_success:
    - bash <(curl -s https://codecov.io/bash)