language: swift
osx_image: xcode9
branches:
  only:
    - master
env:
  matrix:
    - DESTINATION="OS=4.0,name=Apple Watch - 42mm"
    - DESTINATION="OS=11.0,name=iPhone X"      
    - DESTINATION="OS=10.2,name=Apple TV 1080p"   
    - DESTINATION="arch=x86_64"
script:
  - set -o pipefail
  - swiftlint
  - xcodebuild test -enableCodeCoverage YES -project SwiftQueue.xcodeproj -scheme SwiftQueue -destination "$DESTINATION"
after_success:
    - bash <(curl -s https://codecov.io/bash)
